### PR TITLE
Use AVPlayerViewController in AVKit for playing video

### PR DESCRIPTION
**Pull request by trinnguyen**
## Issue:
- Crash on iOS 13
`'NSInvalidArgumentException', reason: 'MPMoviePlayerViewController is no longer available. Use AVPlayerViewController in AVKit.'`

## Solution:
- Use `AVPlayerViewController` instead of `MPMoviePlayerViewController`
- Sample code in: https://github.com/0xced/XCDYouTubeKit#ios-80--tvos-avplayerviewcontroller

### CODE REVIEW

**Comment by dylanhiemstra** [comment]
Merge please?

**Comment by trinnguyen** [comment]
@dylanhiemstra you can add plugin from Git source dirctly while waiting for the merge. Remember to install the Ionic native package afterward

`npm install --save @ionic-native/youtube-video-player`

**Comment by zabojad** [comment]
Guys, I'm using the master version of https://github.com/ihadeed/CordovaYoutubeVideoPlayer and videos on iOS do not play. Instead, I see the video player showing up and hiding. The video is never loaded. I've tried with different videos and the issue is the same. It works fine on Android though...

@trinnguyen  @dylanhiemstra @ihadeed  Do you observe the same issue ?

**Comment by zabojad** [comment]
I solved my problem by executing `pod repo update`. I also forced the XCDYouTubeKit podspec to latest version 2.8.2 in a fork of this plugin:

`<framework src="XCDYouTubeKit" type="podspec" spec="~> 2.8.2" />`

And it works. The problem was that I did not have the latest XCDYouTubeKit version via cocoa pods and that was necessary to get all the latest fixes for ios13...

In case that might help someone else...

@ihadeed that would be great to enable issues on this repo.

**Pull request merged**
